In [1]:
#1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a
#dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical)
#variable. For example, if your categorical variable is age groups and quantitative variable is
#income, then provide summary statistics of income grouped bythe age groups. Create a list
#that contains a numeric value for each response to the categorical variable.

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/content/drive/MyDrive/Datasets/data.csv')
df.head()

   age  income  gender education       city
0   22  280000    Male  Bachelor       Pune
1   25  350000  Female  Bachelor     Mumbai
2   29  480000    Male    Master  Bangalore
3   31  520000  Female    Master      Delhi
4   35  750000    Male       PhD  Hyderabad

In [4]:
grouped_stats = df.groupby("gender")["income"].agg(
    mean="mean",
    median="median",
    minimum="min",
    maximum="max",
    std_dev="std"
)

grouped_stats

            mean    median  minimum  maximum        std_dev
gender
Female  651600.0  510000.0   300000  1600000  372756.399453
Male    866800.0  760000.0   250000  1800000  416390.441773

In [5]:
income_list_by_gender = df.groupby("gender")["income"].apply(list)

income_list_by_gender

gender
Female    [350000, 520000, 410000, 1200000, 300000, 3900...
Male      [280000, 480000, 750000, 900000, 680000, 60000...
Name: income, dtype: object

In [6]:
# 2.Write a Python program to display some basic statistical details like percentile, mean, standard
#deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris- versicolor’ of iris.csv
#dataset.

In [7]:
iris = pd.read_csv("/content/drive/MyDrive/Datasets/Iris.csv")
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
print(iris.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [9]:
iris_stats = iris.groupby("Species").describe()
iris_stats

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [10]:
for species in iris["Species"].unique():
    print(f"\nStatistics for {species}")

    subset = iris[iris["Species"] == species]

    print("Mean:\n", subset.mean(numeric_only=True))
    print("\nStandard Deviation:\n", subset.std(numeric_only=True))
    print("\nPercentiles:\n", subset.quantile([0.25, 0.50, 0.75], numeric_only=True))

Statistics for Iris-setosa
Mean:
 Id               25.500
SepalLengthCm     5.006
SepalWidthCm      3.418
PetalLengthCm     1.464
PetalWidthCm      0.244
dtype: float64

Standard Deviation:
 Id               14.577380
SepalLengthCm     0.352490
SepalWidthCm      0.381024
PetalLengthCm     0.173511
PetalWidthCm      0.107210
dtype: float64

Percentiles:
          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  13.25            4.8         3.125          1.400           0.2
0.50  25.50            5.0         3.400          1.500           0.2
0.75  37.75            5.2         3.675          1.575           0.3

Statistics for Iris-versicolor
Mean:
 Id               75.500
SepalLengthCm     5.936
SepalWidthCm      2.770
PetalLengthCm     4.260
PetalWidthCm      1.326
dtype: float64

Standard Deviation:
 Id               14.577380
SepalLengthCm     0.516171
SepalWidthCm      0.313798
PetalLengthCm     0.469911
PetalWidthCm      0.197753
dtype: float64

Percentiles:
          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  63.25            5.6         2.525           4.00           1.2
0.50  75.50            5.9         2.800           4.35           1.3
0.75  87.75            6.3         3.000           4.60           1.5

Statistics for Iris-virginica
Mean:
 Id               125.500
SepalLengthCm      6.588
SepalWidthCm       2.974
PetalLengthCm      5.552
PetalWidthCm       2.026
dtype: float64

Standard Deviation:
 Id               14.577380
SepalLengthCm     0.635880
SepalWidthCm      0.322497
PetalLengthCm     0.551895
PetalWidthCm      0.274650
dtype: float64

Percentiles:
           Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  113.25          6.225         2.800          5.100           1.8
0.50  125.50          6.500         3.000          5.550           2.0
0.75  137.75          6.900         3.175          5.875           2.3